### ISSUE TITLE
1.502347469329834 instead of 1.5

### ISSUE THREAD

**Issue by interestingLSY** [mind-overflow/gnome-fs-duplicate-cursor-fix#2]
Hi dev!

I'm using Lenovo Xiaoxin Pro16, which has a screen of resolution 2560x1600. I tried to set 'scale' to 1.5 in config.yml but the script don't work (After executing the script, the scale is 100% instead of 150%). Here is the output:

```
Loading config...
Done!
Enabled: true
Delay: 10000
Monitor name: eDP
Monitor scale: 1.502347469329834
Main element: monitors
1 - Current node: configuration
    2 - Current node: logicalmonitor
        3A - current node: scale
            Current scale: 1.5
        3B - current node: monitor
            4 - current node: monitorspec
                    5 - current node: connector
                        Current connector: eDP
Restarting GNOME...
line: bs true ""
exit: 0
Restarting GNOME...
line: bs true ""
exit: 0
```

I fixed that by setting 'scale' to 1.502347469329834 in config.yml. Now the script works perfectly.

**Comment by mind-overflow** [comment]
Thanks! I'll look into it, but the issue will most likely be related to xrandr rather than this program itself, as it simply loads the values and passes them. maybe (?) it has to do with pixel dimensions not matching perfectly at 1.5?

**Comment by mind-overflow** [comment]
Closing this as I've had no other reports and it seems to be related to your particular case scenario (hardware, sw configuration)...
Thanks for taking the time to report this though!
