### ISSUE TITLE
Duplicate cursor gets stuck in the middle of the screen after utilising script 

### ISSUE THREAD

**Issue by Nakamerica** [mind-overflow/gnome-fs-duplicate-cursor-fix#5]
Hi, i ran the script and followed the installation instructions, but now, on startup, the duplicate cursor gets stuck on the middle of the screen (at the password fill in box), while the working cursor pops up on the right bottom edge of the screen. Not sure what's going wrong. Any help will be appreciated. A screenshot is attached that will hopefully give some idea of the location of the duplicate pointer. It's basically bang in the middle of the screen...
![Screenshot from 2022-01-21 01-57-03](https://user-images.githubusercontent.com/88226614/150416764-5d887af4-5ecd-48ec-b208-91e5777c2888.png)

**Comment by mind-overflow** [comment]
Hey! Sorry if I seem blind, but I can't see any cursor in the attached screenshot.  
Anyway, what happens if you try to manually run the program after logging in? Does it fix the issue?  
If it does, then probably there's an issue with the automatic launch and we'll have to look into that.

**Comment by Nakamerica** [comment]
> 

sorry i couldn't get back... i switched to pop os now so I don't think I'll be able to try out what you recommended. 


apologies for wasting time with this issue.
