### ISSUE TITLE
Solved by switch to ubuntu on wayland

### ISSUE THREAD

**Issue by vincentkace** [mind-overflow/gnome-fs-duplicate-cursor-fix#6]
On the startup page which I have to enter the password, switch to _ubuntu on wayland_ by a setting icon on the right below corner, and I solved the duplicate cursor problem.

**Comment by mind-overflow** [comment]
Thanks! Yes, Wayland is definitely a solution, but not applicable to everyone. Unfortunately, in my case, I have a multi-screen setup with a mix of HiDPI and Low DPI monitors - which is a very difficult case-scenario. Unfortunately, while Wayland *does* support fractional scaling, most apps don't support Wayland's specific fractional scaling, and thus look incredibly blurry. On a 4K screen, this is painful to look at. Unfortunately, my only solution is to use Xorg, which has this bug (and worse performance, as it renders everything in higher resolution and then downscales to remove the blur).
